---
output: pdf_document
documentclass: exam
header-includes: 
  - \usepackage{multicol}
---
\pagestyle{headandfoot}
\firstpageheader{College and Advanced Algebra\\O. D. Hombrebueno}{Nueva Vizcaya State University\\College of Teacher Education}{Midterm Exam\\October 12, 2018}
\runningheader{}{}{}
\firstpagefooter{}{}{}
\runningfooter{College and Advanced Algebra}{Midterm Exam}{Page \thepage\ of \numpages}
\runningfootrule

\makebox[4in]{Name:\enspace\hrulefill}

\makebox[3in]{Course and Year:\enspace\hrulefill}

\vspace{5mm}

**Part 1.** Insert $\in$ or $\notin$ in the blank to make the statement correct.

\begin{multicols}{5}
\begin{enumerate}
\setlength\fillinlinelength{.30in}
\item 15 \fillin $N$
\item 1.4142 \fillin $H$
\item 0 \fillin $Q$
\item 2007 \fillin $J$
\item -5 \fillin $H$
\end{enumerate}
\end{multicols}

**Part 2.** Use the symbol $\subseteq$ to give a correct statement involving the two sets.

\begin{multicols}{5}
\begin{enumerate}
\item $N$ and $Q$
\item $R$ and $Q$
\item $J$ and $N$
\item $H$ and $R$
\item ${0}$ and $J$
\end{enumerate}
\end{multicols}

\vspace{2mm}

**Part 3.** Determine which of the sets $N$, $J$, $Q$, $H$, $R$, and $\emptyset$ is equal to the given set. 

\begin{multicols}{5}
\begin{enumerate}
\item $Q\cap R$
\item $H\cap R$
\item $Q\cup R$
\item $H\cap Q$
\item $J\cap N$
\end{enumerate}
\end{multicols}

\vspace{2mm}

**Part 4.** Use set builder notation and one or more of the symbols $<$, $>$, $\le$, and $\ge$ to denote the set.

1. The set of all $y$ between $-12$ and $-3$.
2. The set of all $y$ such that $y$ is greater than or equal to $-26$ and less than $-16$.
3. The set of all $x$ such that $2x+4$ is nonnegative.
4. The set of all $a$ such that $a-2$ is greater than $-5$ and less than or equal to $7$.
5. The set of all $z$ such that $2z+5$ is between and including $-1$ and $15$.

\vspace{1in}

**Part 5.** Show the set on the number line and represent the set by interval notation.

1. $\{x|-4<x\le 4\}$
2. $\{x|x>2\text{ and }x<12\}$
3. $\{x|x<3\text{ or }x>6\}$
4. $\{x|x\ge -5\}\cap\{x|x\le 5\}$
5. $\{x|x>2\}\cup\{x|x>10\}$

**Part 6.** Write the number without absolute value bars.

\begin{multicols}{5}
\begin{enumerate}
\item $|3-\sqrt{3}|$
\item $\left|-\dfrac{3}{4}\right|$
\item $\left|\dfrac{1}{3}\right|$
\item $|-8|$
\item $|3-\pi|$
\end{enumerate}
\end{multicols}

**Part 7.** Use laws of exponents to write the expression so that each variable occurs only once and all the exponents are positive. None of the denominators is zero.

\begin{multicols}{2}
\begin{enumerate}
\item $a^{-3} \cdot a^{6}$
\item $\dfrac{y^{5}}{y^{-7}}$
\item $(s^{5}t^{-1})^{-2}$
\item $\left(\dfrac{x^{-1}}{y^{3}}\right)^{-4}$
\item $-7(-x^{6}y)(-x^{6}y^{5})$
\item $(2x^{2})^{3}(3y^{3})^{2}$
\item $(4s^{4})^4(2t^{3})^{3}$
\item $\dfrac{(20r^{2}s^{3}t^{4})(2r^{2}s^{2}t)}{(-4rst)(3rs^{4}t^{2})}$
\item $\dfrac{3^{-2}x^{-4}y^{0}}{(3x^{2}y^{3})^{-4}}$
\item $\left(\dfrac{3x^{-1}y^{2}z^{3}}{2x^{-3}y^{-2}z^{-1}}\right)^{-1}$
\end{enumerate}
\end{multicols}

**Part 8.** Simplify the algebraic expression. For items 8, 12, and 23, $n$ is a positive integer. For items 21-25, none of the divisor is zero.

\begin{enumerate}
\item $4x^2-5x+6x^2-2x$
\item $2(3u-4v)-(5u-3v)$
\item $3(-t^2+3st-2s^2)-2(7t^2-st-s^2)$
\item $3(2w-3z)-[w-z-(w+z)]$
\item $(4x^3-7x^2+2x-4)+(3x^3+8x^2+3x-7)$
\item $-(4z^5-6z^3+z-8)-(2z^5+7z^4-z^2+4z+1)$
\item $2xyz^2(3xz-6yz-xy-1)$
\item $3x^{2n}(x^{n+1}-4x^n+5)$
\item $(y+8)(4y-3)$
\item $(2x^2-5y^2)(-3x^2+y^2)$
\item $(b-3b^2+7)(5b^2+2-3b)$
\item $(3x^{2n}+y^n)(4x^{2n}-5y^n)$
\item $(y-2)(y+7)$
\item $(5t+4)^2$
\item $(w+6)(w-6)$
\item $(6x-y)(3x+2y)$
\item $(t^2-5)(t^2+9)$
\item $(4x^2-3y^2)^2$
\item $(3r-10s)(3r+10s)$
\item $(7a^2-2b^2)(5a^2+3b^2)$
\item $\dfrac{-48y^3+30y^2-18y}{6y}$
\item $\dfrac{-24a^3b^3c^4+32a^2b^4c^2-16a^5b^3c^3}{8a^2b^2c^2}$
\item $\dfrac{16t^{4n}-64t^{6n}}{2t^{2n}}$
\item $\dfrac{a^3-3a^2-a+3}{a-2}$
\item $\dfrac{t^3-7t-6}{t+2}$
\end{enumerate}