---
title: "Polynomials"
output:
  pdf_document: null
header-includes:
- \newtheorem{theorem}{Theorem}
- \newtheorem{definition}{Definition}
- \usepackage{polynom}
---
# Introduction

Recall that a **variable** is a symbol used to represent any element of a given domain.

A **constant** is a symbol whose domain contains only one element.

*Example*

$$6x^{2}+2x+5$$

Sometimes letters are used as symbols for constants if the letters designate fixed but unspecified numbers.

*Example*

$$ax+b$$

**Algebraic expression** is used to mean a constant, a variable, or a combination of variables and constants involving a finite number of indicated operations (addition, subtraction, multiplication, division, raising to a power, and extraction of a root) on them.

*Example*

$$3x^{2}y^{5}\qquad 5x^{2}-8x+2\qquad \frac{3x^{2}-6xy+y^{2}}{x+2y}\qquad \frac{\sqrt{x+y}-4}{(x+2)^{3}-\sqrt[3]{x}}$$

A **polynomial** is an algebraic expression involving only nonnegative-integer powers of one or more variables and containing no variable in a denominator.

*Example*

$$2x\qquad 5x^{2}-8x+2 \qquad 3x^{2}y^{5}\qquad 8xy-7x+y-3$$

A **term** of a polynomial is a constant or a constant multiplied by nonnegative-integer powers of variables.Any factor of a product is said to be the **coefficient** of the other factors. If a coefficient is a constant then it is called a **constant coefficient**. Terms that may differ only in their constant coefficients are called **like terms**. Like terms of a polynomial are combined algebraically by using the distributive law.

*Example*

\begin{align*}
  6x^{2}+x+7+3x^{2}-4x &= (6x^{2}+3x^{2})+(x-4x)+7\\
   &= (6+3)x^{2}+(1-4)x+7\\
   &= 9x^{2}-3x+7
\end{align*}

A **monomial** is a polynomial with one term. A **binomial** is a polynomial with two terms and if it has three terms, it is called a **trinomial**.

The **degree** of a monomial in one variable is the exponent of the variable. If it has two or more variables, the degree is the sum of the exponents of the variables. The degree of a constant is zero. The constant $0$ has no degree. The degree of a polynomial is the degree of the term with the highest degree.

# Simplifying Polynomials

Some polynomials can be simplified using distributive laws:

\begin{align*}
  ax+bx &= (a+b)x\\
  ax-bx &= (a-b)x\\
  ax+bx+cx &= (a+b+c)x
\end{align*}

and so on.

Distributive laws can be used to write the product of a monomial and a polynomial.

$$a(x+y+z)=ax+ay+az$$

## Special Products

***Special product 1:*** $(x+a)(x+b)=x^{2}+(a+b)x+ab$

***Special product 2:*** $(x+y)^{2}=x^{2}+2xy+y^{2}$

***Special product 3:*** $(x+y)(x-y)=x^{2}-y^{2}$

***Special product 4:*** $(ax+by)(cx+dy)=acx^{2}+(ad+bc)xy+bdy^{2}$

Special products 1 to 4 are called **identities** because a true statement is obtained if any real number is substituted for a variable.

## Division

If $d\ne 0$, then

$$\frac{u+v+w}{d}=\frac{u}{d}+\frac{v}{d}+\frac{w}{d}.$$

### Division Algorithm

If $x\ne \frac{4}{3}$, then

\[
\polylongdiv{6x^2+13x-28}{3x-4}
\]

**1.** We divide $6x^2$ (the first term of the dividend) by $3x$ (the first term of the divisor) to obtain $2x$ (the first term of the quotient).  
**2.** We multiply $3x-4$ (the divisor) by $2x$ to obtain the product $6x^2-8x$, which we write with opposite signs under the like terms of the dividend.  
**3.** We add and obtain the remainder $21x-28$, which we consider as a new dividend.  
**4.** We divide $21x$ (the first term of the new dividend) by $3x$ (the first term of the divisor) and obtain $7$ (the second term of the quotient).  
**5.** We multiply $3x-4$ by 7 to obtain the product $21x-28$, which we write with opposite signs under the new dividend and add. We obtain the remainder 0 for this particular problem.

*Example*

If $z\ne 5$, then

\polyset{vars=xyz,
delims={[}{]}}

\[
\polylongdiv{3z^{3}-11z^{2}-18z-6}{z-5}
\]

We write the result as

$$\frac{3z^3-11z^2-18z-6}{z-5}=3z^2+4z+2+\frac{4}{z-5}$$

# Practice Items

**1.** Simplify the algebraic expression.

  a. $4x^2-5x+6x^2-2x$
  
  b. $2(3u-4v)-(5u-3v)$
  
  c. $3(-t^2+3st-2s^2)-2(7t^2-st-s^2)$
  
  d. $3(2w-3z)-[w-z-(w+z)]$
  
**2.** Add the two polynomials and subtract the second polynomial from the first.

  a. $4x^3-7x^2+2x-4$; $3x^3+8x^2+3x-7$
  
  b. $2z^5+7z^4-z^2+4z+1$; $4z^5-6z^3+z-8$
  
**3.** Find the product. For b. and h., $n$ is a positive integer.

  a. $2xyz^2(3xz-6yz-xy-1)$
  
  b. $3x^{2n}(x^{n+1}-4x^n+5)$
  
  c. $(y+8)(4y-3)$
  
  d. $(2x^2-5y^2)(-3x^2+y^2)$
  
  e. $-4(9a-5b)(a+3b)$
  
  f. $(2u-5v)(4u^2-uv-3v^2)$
  
  g. $(b-3b^2+7)(5b^2+2-3b)$
  
  h. $(3x^{2n}+y^n)(4x^{2n}-5y^n)$

\vspace{.5in}
  
**4.** Apply special products 1 through 4 to find the indicated product. Identify which special product applies.

  a. $(y-2)(y+7)$
  
  b. $(5t+4)^2$
  
  c. $(w+6)(w-6)$
  
  d. $(6x-y)(3x+2y)$
  
  e. $(t^2-5)(t^2+9)$
  
  f. $(4x^2-3y^2)^2$
  
  g. $(3r-10s)(3r+10s)$
  
  h. $(7a^2-2b^2)(5a^2+3b^2)$
  
**5.** Find the quotient. None of the divisor is zero.

  a. $\dfrac{8x^2-28x^4}{4x^2}$
  
  b. $\dfrac{-48y^3+30y^2-18y}{6y}$
  
  c. $\dfrac{-24a^3b^3c^4+32a^2b^4c^2-16a^5b^3c^3}{8a^2b^2c^2}$
  
  d. $\dfrac{16t^{4n}-64t^{6n}}{2t^{2n}}$
  
  e. $\dfrac{a^3-3a^2-a+3}{a-2}$
  
  f. $\dfrac{t^3-7t-6}{t+2}$
  
  g. $\dfrac{y^3-6y+5}{y^2+3y-2}$
  
  h. $\dfrac{2x^3+4x^2-5}{x^2+3}$
